---
title: "Modeling Lake Trophic State: A Data Mining Approach"
bibliography: LakeTrophicModelling.bib
layout: preprint
linenumbers: false
csl: plos.csl
documentclass: elsarticle
output: 
  pdf_document:
    template: elsarticle.latex
    keep_tex: true
    fig_caption: true
author: 
  - name: Jeffrey W. Hollister
    affiliation: aed
    email: hollister.jeff(at)epa.gov
    footnote: Corresponding author
  - name: W. Bryan Milstead 
    affiliation: aed
  - name: Betty J. Kreakie
    affiliation: aed
address: 
  - code: aed
    address: | 
      US Environmental Protection Agency
      Office of Research and Development
      National Health and Environmental Effects Research Laboratory
      Atlantic Ecology Division
      27 Tarzwell Drive 
      Narragansett, RI, 02879, USA 
abstract: | 
    Cyanobacteria are a primary taxonomic group associated with harmful algal blooms
    in lakes. Understanding the drivers of cyanobacteria presence has important
    implications for lake management and for the protection of human and ecosystem
    health.  Chlorophyll a concentration, a measure of the biological productivity of
    a lake, is one such driver and is largely, although not exclusively, determined by
    nutrient inputs.   As nutrient inputs increase, productivity increases and lakes
    transition from low trophic state (e.g. oligotrophic) to higher trophic states 
    (e.g. eutrophic).  These broad trophic state classifications are good predictors
    of ecosystem health and ecosystem services/disservices (e.g. recreation, 
    aesthetics, fisheries, and harmful algal blooms).  Thus, our existing models of
    trophic state might be used to predict cyanobacteria.   We test this idea and
    compare the performance of two models of trophic state (as determined by 
    chlorophyll a concentration).   Model 1 estimates trophic state with nutrients
    alone and model 2 uses nutrients plus landscape composition within the lake
    watershed.  We use random forest models to determine the out of bag (OOB) error
    for both models and to compare the error associated with each variable.   We use
    the best model to compare presence/absence of several cyanobacteria taxa relative
    to trophic state. Our preliminary results suggest that Model 1 (nutrients alone)
    has an OOB error rate of 42.0%.  Model 2 (nutrients plus landscape variables)
    improves the OOB error rate to 36.1%.  Both Nitrogen and Phosphorus were found to
    be important and, of the landscape variables, percent agriculture, percent
    developed, and percent forest explained the most additional variation.  Expanding
    these preliminary results to include cyanobacteria taxa indicates that 
    cyanobacteria are significantly more likely to be found in highly eutrophic lakes.
    These results suggest that predictive models of lake trophic state may be improved
    with additional information on the landscape surrounding lakes and that those
    models provide additional information on the presence of potentially harmful
    cyanobacteria taxa.
---
<!--
%\VignetteEngine{knitr::rmarkdown}
%\VignetteIndexEntry{Lake Trophic Modelling}
-->


##Introduction
Cyanobacteria are an important taxonomic group associated with harmful algal blooms in lakes. Understanding the drivers of cyanobacteria presence has important implications for lake management and for
 the protection of human and ecosystem health.  Chlorophyll a concentration, a measure of the biological productivity of a lake, is one such driver and is largely, although not exclusively, determined
 by nutrient inputs.   As nutrient inputs increase, productivity increases and lakes transition from low trophic state (e.g. oligotrophic) to higher trophic states (e.g. hypereutrophic).  These broad
trophic state classifications are associated with ecosystem health and ecosystem services/disservices (e.g. recreation, aesthetics, fisheries, and harmful algal blooms).  Thus, models of trophic state
 might be used to predict things like cyanobacteria.

We have three goals for this preliminary research:

1. Build and assess models of lake trophic state
2. Assess ability to predict trophic state in lakes without available *in situ* water quality data
3. Explore association between cyanobacteria and trophic in order to expand models.

##Data and Modeling Methods

**Data**

We utilize four primary sources of data for this study. These are outlined below and in Table 1.

1. National Lakes Assessment (NLA) 2007: The NLA data were collected during the summer of 2007 and the final data were released in 2009.  With consistent methods and metrics collected at 1056 location
s across the conterminous United States (Map 1), the NLA provides a unique opportunity to examine broad scale patterns in lake productivity.  The NLA collected data on biophysical measures of lake wat
er quality and habitat.  For this analysis we primarily examined the water quality measurements from the NLA [@usepa2009national].
2. National Land Cover Dataset (NLCD) 2006: The NLCD is a nationally collected land use land cover dataset.  We collected total land use land cover and total percent impervious surface within a 3 kilo
meter buffer surrounding the lake to examine larger landscape-level effects [@homer2004development;@xian2009updating].
3. Modeled lake morphometry: Various measures of lake morphometry (i.e. depth, volume, fetch, etc.) are important in understanding lake productivity, yet many of these data are difficult to obtain for
 large numbers of lakes over broad regions.  To add this information we modeled lake morphometry [@hollister2010volume;@hollister_predicting_2011;@Lakmorpho2014;@NLMDInPrep].
4. Estimated Cyanobacteria Biovolumes: Cyanobacteria biovolumes are a truer measure of Cyanobacteria dominance than abundance as there is great variability in the size within and between species.  To a
ccount for this, Beaulieu *et al.* [-@beaulieu2013nutrients] used literature values to estimate biovolumes for the taxa in the NLA.  They shared this data and we have summed that information on a per-
lake basis.

##References